import { assetPaths } from '../lib/assets';
import type { PartnerProfile } from '../types/content';

export const partnerProfiles: PartnerProfile[] = [
  {
    name: '1590 Energy Corp',
    logo: assetPaths.partners.logos.energy1590,
    coverImg: assetPaths.partners.covers.energy1590,
    location: 'Philippines',
    year: '2018-Ongoing',
    category: 'Energy & Infrastructure',
    description: '1590 Energy Corp operates crucial power facilities, specializing in reliable energy generation and critical infrastructure maintenance.',
    scope: [
      'Fabrication, Insulation, blasting and painting for piping, chimney and duct',
      'Shutdown activities for yearly programs',
      'Erection of duct, pipe and chimney',
    ],
    website: 'https://www.1590energy.com',
  },
  {
    name: 'AG&P',
    logo: assetPaths.partners.logos.agnp,
    coverImg: assetPaths.partners.covers.agp,
    location: 'Philippines / Global',
    year: '2013',
    category: 'Heavy Industry & Modular Construction',
    description: 'Atlantic, Gulf & Pacific (AG&P) is a global leader in modular industrial construction, delivering complex infrastructure solutions for the energy and resources sectors.',
    scope: ['Pipe and structural fabrication for Samsung Engineering, Yamal Project'],
    website: 'https://www.agpglobal.com',
  },
  {
    name: 'Dubai World',
    logo: assetPaths.partners.logos.dubaiWorld,
    coverImg: assetPaths.partners.covers.dubaiWorld,
    location: 'Dubai, UAE',
    year: '2006-2009',
    category: 'Maritime & Shipping',
    description: 'One of the most prolific shipyards in the Middle East, Dubai Drydocks World handles the repair, conversion, and construction of large marine vessels and offshore rigs.',
    scope: [
      'Design, supply and installation for Blasting and painting shop',
      'Manufacture and supply for internal tank coating equipment',
    ],
    website: 'https://www.drydocks.gov.ae/',
  },
  {
    name: 'Hanjin Heavy Industries',
    logo: assetPaths.partners.logos.hanjin,
    coverImg: assetPaths.partners.covers.hanjinDetail,
    location: 'Subic, Philippines',
    year: '2010',
    category: 'Shipbuilding & Heavy Industry',
    description: 'One of the world\'s leading shipbuilders, Hanjin Heavy Industries operates major shipyards specializing in large-scale commercial vessel construction and marine engineering.',
    scope: [
      'Design, supply, and installation for blasting & painting shops',
      'Internal tank coating for chemical tankers',
      'Supply of marine components and accessories',
    ],
    website: 'https://www.hjsc.co.kr',
  },
  {
    name: 'International Maritime Industries (IMI)',
    logo: assetPaths.partners.logos.imi,
    coverImg: assetPaths.partners.covers.imi,
    location: 'Saudi Arabia',
    year: '2025-Ongoing',
    category: 'Maritime & Offshore',
    description: 'IMI is the largest maritime facility in the MENA region, providing world-class shipbuilding, rig manufacturing, and maintenance services.',
    scope: [
      'Preparation of detailed drawings for production',
      'Supply and installation of equipment and facilities for blasting and painting',
    ],
    website: 'https://www.imi-ksa.com',
  },
  {
    name: 'Mitsubishi Power',
    logo: assetPaths.partners.logos.mitsubishiPower,
    coverImg: assetPaths.partners.covers.mitsubishiPower,
    location: 'Global Operations',
    year: '2014',
    category: 'Energy & Power Systems',
    description: 'Mitsubishi Power is a global leader in power generation solutions, providing advanced gas turbines, steam turbines, and comprehensive aftermarket services.',
    scope: ['Supply of labor & material for San Roque region'],
    website: 'https://power.mhi.com',
  },
  {
    name: 'JG Summit',
    logo: assetPaths.partners.logos.jgSummit,
    coverImg: assetPaths.partners.covers.jgSummit,
    location: 'Philippines',
    year: '2014',
    category: 'Petrochemical',
    description: 'JG Summit Petrochemical Group operates one of the largest vertically integrated petrochemical complexes in Southeast Asia.',
    scope: [
      'Industrial surface treatment for chemical facilities',
      'Piping system maintenance',
      'Structural Steel Engineering',
    ],
    website: 'https://www.jgsummitpetrochemical.com',
  },
  {
    name: 'Qatar Petroleum',
    logo: assetPaths.partners.logos.qatarPetroleum,
    coverImg: assetPaths.partners.covers.qatarPetroleum,
    location: 'Qatar',
    year: '2009',
    category: 'Oil & Gas',
    description: 'QatarEnergy (formerly Qatar Petroleum) is the state-owned petroleum company of Qatar, managing all phases of the oil and gas industry.',
    scope: ['Supply of Blasting and Painting Equipment'],
    website: 'https://www.qatarenergy.qa',
  },
  {
    name: 'Siemens Energy',
    logo: assetPaths.partners.logos.siemensEnergy,
    coverImg: assetPaths.partners.covers.siemensEnergy,
    location: 'Global',
    year: '2018-Ongoing',
    category: 'Energy Technology',
    description: 'Siemens Energy is one of the world\'s leading energy technology companies, driving the transition to sustainable energy systems.',
    scope: [
      'Electromechanical Installation & Commissioning of duct systems',
      'Shutdown maintenance activities',
    ],
    website: 'https://www.siemens-energy.com',
  },
  {
    name: 'Shell',
    logo: assetPaths.partners.logos.shell,
    coverImg: assetPaths.partners.covers.shell,
    location: 'Global Operations',
    year: '2014',
    category: 'Energy & Petrochemical',
    description: 'Shell is an international energy company with expertise in the exploration, production, refining, and marketing of oil and natural gas.',
    scope: ['JGC PSPC TABANGAO REFINERY STRUCTURE'],
    website: 'https://www.shell.com',
  },
];
